DROP TABLE "CHAT_DETAIL";
DROP TABLE "CHAT";
DROP TABLE "MEMBER";

-- MEMBER TABLE
CREATE TABLE "MEMBER" (
    USER_ID VARCHAR2(20) PRIMARY KEY,
    USER_PWD VARCHAR2(20) NOT NULL,
    "NAME" VARCHAR2(20) NOT NULL,
    ADDRESS VARCHAR2(100) NOT NULL,
    DETAIL_ADDRESS VARCHAR2(50) NOT NULL,
    BIRTH_DATE VARCHAR2(30),
    GENDER VARCHAR2(1) NULL CHECK(GENDER IN('F', 'M')),
    EMAIL VARCHAR2(100) NOT NULL,
    STATUS VARCHAR2(1)DEFAULT 'N' NOT NULL
);
-- COMMENT
COMMENT ON COLUMN MEMBER."USER_ID" IS '아이디';
COMMENT ON COLUMN MEMBER."USER_PWD" IS '비밀번호';
COMMENT ON COLUMN MEMBER."NAME" IS '이름';
COMMENT ON COLUMN MEMBER."ADDRESS" IS '주소';
COMMENT ON COLUMN MEMBER."DETAIL_ADDRESS" IS '상세주소';
COMMENT ON COLUMN MEMBER.BIRTH_DATE IS '생년월일';
COMMENT ON COLUMN MEMBER.GENDER IS '성별';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.STATUS IS '탈퇴여부';

--CHAT
CREATE TABLE "CHAT" (
    CHAT_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(20) NOT NULL REFERENCES MEMBER(USER_ID),
    TITLE VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(100)
);
-- COMMENT
COMMENT ON COLUMN CHAT.CHAT_NO IS '채팅글번호';
COMMENT ON COLUMN CHAT.USER_ID IS '작성자';
COMMENT ON COLUMN CHAT.TITLE IS '제목';
COMMENT ON COLUMN CHAT.CONTENT IS '내용';

--CHAT_DETAIL
CREATE TABLE "CHAT_DETAIL" (
    DETAIL_NO NUMBER PRIMARY KEY,
    CHAT_NO NUMBER NOT NULL REFERENCES CHAT(CHAT_NO),
    USER_ID VARCHAR2(20) NOT NULL REFERENCES MEMBER(USER_ID),
    "CONTENT" VARCHAR2(300) NOT NULL,
    ORIGIN_NAME VARCHAR2(2000),
    CHANGE_NAME VARCHAR2(2000)
);

-- COMMENT
COMMENT ON COLUMN CHAT_DETAIL.DETAIL_NO IS '채팅번호';
COMMENT ON COLUMN CHAT_DETAIL.CHAT_NO IS '글번호';
COMMENT ON COLUMN CHAT_DETAIL.USER_ID IS '대화작성자';
COMMENT ON COLUMN CHAT_DETAIL."CONTENT" IS '내용';
COMMENT ON COLUMN CHAT_DETAIL.ORIGIN_NAME IS '원래파일이름';
COMMENT ON COLUMN CHAT_DETAIL.CHANGE_NAME IS '바뀐파일이름';

