DROP TABLE "CHAT_CONTENT";
DROP TABLE "CHAT_DETAIL";
DROP TABLE "CHAT";
DROP TABLE "MEMBER";
DROP SEQUENCE SEQ_CNO;
DROP SEQUENCE SEQ_DNO;


-- MEMBER TABLE
CREATE TABLE "MEMBER" (
    USER_ID VARCHAR2(20) PRIMARY KEY,
    USER_PWD VARCHAR2(2000) NOT NULL,
    "NAME" VARCHAR2(20) NOT NULL,
    ADDRESS VARCHAR2(100) NOT NULL,
    DETAIL_ADDRESS VARCHAR2(50) NOT NULL,
    BIRTH_DATE VARCHAR2(30),
    GENDER VARCHAR2(1) NULL CHECK(GENDER IN('F', 'M')),
    EMAIL VARCHAR2(100) NOT NULL,
    STATUS VARCHAR2(1)DEFAULT 'N' NOT NULL
);
-- COMMENT
COMMENT ON COLUMN MEMBER."USER_ID" IS '아이디';
COMMENT ON COLUMN MEMBER."USER_PWD" IS '비밀번호';
COMMENT ON COLUMN MEMBER."NAME" IS '이름';
COMMENT ON COLUMN MEMBER."ADDRESS" IS '주소';
COMMENT ON COLUMN MEMBER."DETAIL_ADDRESS" IS '상세주소';
COMMENT ON COLUMN MEMBER.BIRTH_DATE IS '생년월일';
COMMENT ON COLUMN MEMBER.GENDER IS '성별';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.STATUS IS '탈퇴여부';

--CHAT
CREATE TABLE "CHAT" (
    CHAT_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(20) NOT NULL REFERENCES MEMBER(USER_ID),
    TITLE VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(100),
    STATUS VARCHAR2(1) DEFAULT 'N' NOT NULL
);
-- COMMENT
COMMENT ON COLUMN CHAT.CHAT_NO IS '글번호';
COMMENT ON COLUMN CHAT.USER_ID IS '작성자';
COMMENT ON COLUMN CHAT.TITLE IS '제목';
COMMENT ON COLUMN CHAT.CONTENT IS '내용';
COMMENT ON COLUMN CHAT.STATUS IS '삭제여부';

--CHAT_DETAIL
CREATE TABLE "CHAT_DETAIL"(
    DETAIL_NO NUMBER PRIMARY KEY, 
    CHAT_NO NUMBER NOT NULL REFERENCES CHAT(CHAT_NO),
    USER_ID1 VARCHAR2(20) NOT NULL REFERENCES MEMBER(USER_ID),
    USER_ID2 VARCHAR2(20) NOT NULL REFERENCES MEMBER(USER_ID)
);
-- COMMENT
COMMENT ON COLUMN CHAT_DETAIL.DETAIL_NO IS '채팅번호';
COMMENT ON COLUMN CHAT_DETAIL.CHAT_NO IS '글번호';
COMMENT ON COLUMN CHAT_DETAIL.USER_ID1 IS '글 작성자';
COMMENT ON COLUMN CHAT_DETAIL.USER_ID2 IS '참여자';

--CHAT_CONTENT
CREATE TABLE "CHAT_CONTENT" (
    DETAIL_NO NUMBER REFERENCES CHAT_DETAIL(DETAIL_NO),
    CHAT_NO NUMBER NOT NULL REFERENCES CHAT(CHAT_NO),
    USER_ID VARCHAR2(20) NOT NULL REFERENCES MEMBER(USER_ID),
    "CONTENT" VARCHAR2(300) NOT NULL,
    ORIGIN_NAME VARCHAR2(2000),
    CHANGE_NAME VARCHAR2(2000),
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL
);

-- COMMENT
COMMENT ON COLUMN CHAT_CONTENT.DETAIL_NO IS '채팅상세번호';
COMMENT ON COLUMN CHAT_CONTENT.CHAT_NO IS '채팅방번호';
COMMENT ON COLUMN CHAT_CONTENT.USER_ID IS '대화작성자';
COMMENT ON COLUMN CHAT_CONTENT."CONTENT" IS '내용';
COMMENT ON COLUMN CHAT_CONTENT.ORIGIN_NAME IS '원본파일이름';
COMMENT ON COLUMN CHAT_CONTENT.CHANGE_NAME IS '바뀐파일이름';
COMMENT ON COLUMN CHAT_CONTENT.CREATE_DATE IS '작성일';

-- cert 테이블
create table cert(
	who varchar2(24),
	secret varchar2(6),
	when date not null,
	primary key (who, secret)
);

CREATE SEQUENCE SEQ_CNO
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1;
CREATE SEQUENCE SEQ_DNO
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1;